"""
This modules computes the confidence intervals with the Bootstrap method. It consists on realizing
multiple bootstraped PCAs to compute the confidence intervals. The method is adapted fromn this
reference:

Babamoradi, H., van den Berg, F., & Rinnan, Å. (2013). Bootstrap based confidence limits in
principal component analysis—A case study. Chemometrics and Intelligent Laboratory Systems, 120,
97‑105. https://doi.org/10.1016/j.chemolab.2012.10.007
"""

from typing import List
from pandas import DataFrame
from tqdm import tqdm
from numpy import full, hstack, concatenate
from numpy.typing import NDArray

from stats import generate_bootstraped_dataset

NUMBER_OF_SAMPLES = 2000

def bootstrap_indicators(indicators: NDArray) -> List[NDArray]:
    """
    Draws the necessary bootsraped indicators to perform the computation of confidence intervals.

    Args:
        - indicators: The indicators to bootstrap.
    
    Returns: A three dimensional array in which the first index represents the number of the
        bootstrap sample. The second index represents the row (observation) and the third index
        returns the value of an indicator.
    """

    bootstraped = []
    for _ in tqdm(range(NUMBER_OF_SAMPLES), "Generating Bootstrap samples", leave=False):
        bootstraped.append(generate_bootstraped_dataset(indicators))

    return bootstraped

def bootstraped_indicators_to_dataframe(
    bootstraped_indicators: List[NDArray],
    codes: List[str]
) -> DataFrame:
    """
    Converts the bootstraped indicators into a dataframe to be later saved into a CSV file.
    
    Args:
        - bootstraped_indicators: The bootstraped indicators generated by `bootstrap_indicators`.
            The three dimensional array will be flattened to a two dimension array.
        - codes: The list of indicator identifiers to show in the header of the dataframe.

    Return: The converted dataframe.
    """

    flattened_indicators = flatten(bootstraped_indicators)
    columns = ['Bootstrap sample number'] + codes
    return DataFrame(flattened_indicators, columns=columns)

def jacknifed_indicators_to_dataframe(
    jacknifed_indicators: List[NDArray],
    codes: List[str]
) -> DataFrame:
    """
    Converts the jacknifed indicators into a dataframe to be later saved into a CSV file.
    
    Args:
        - jacknifed_indicators: The jacknifed indicators generated by `jacknife`.
            The three dimensional array will be flattened to a two dimension array.
        - codes: The list of indicator identifiers to show in the header of the dataframe.

    Return: The converted dataframe.
    """

    flattened_indicators = flatten(jacknifed_indicators)
    columns = ['Jacknife number'] + codes
    return DataFrame(flattened_indicators, columns=columns)

def flatten(data: List[NDArray]) -> NDArray:
    """
    Flattens a three-dimensional array into a two-dimensional array. The index of the third
        dimension is added as a row to the two dimension array.

    Args:
        - data: The data to convert in a two-dimensional array.

    Return: The flattened array. The first column of this array correspond to the index of the third
        dimension.
    """
    flattened: NDArray = None
    for i, sample in tqdm(enumerate(data), "Flattening data.", leave=False):
        index_column = full((len(data[i]), 1), i + 1)
        entries = hstack((index_column, sample))
        flattened = entries if flattened is None else concatenate((flattened, entries))

    return flattened
