"""
The main module contains the main program of the indicator calculation.

A typical program execution will query Eurostat databases, merge the collected datasets into a
single dictionary, compute the elements necessary for the integrated subjective-objective approach,
and compute the confidence intervals from the principal component analysis. Note that only the
degree of independence for aggregation, the confidence intervals and the subjective approach are
computed by the program. The remainder should be set up in a spreadsheet software. All data
generated by the program is saved in a file.
"""

from pandas import DataFrame
from numpy import array

from merger import merge_datasets, convert_dataset_to_dataframe
from data import load_config, save_csv
from independance import get_degrees_of_independance, prepare_dataframe_for_pca
from subjective import (
    get_scores_for_indicators,
    get_comparison_matrices,
    get_subjective_weights,
    convert_scores_to_dataframe,
    convert_weights_to_dataframe,
    convert_consistency_to_dataframe
)
from contribution import make_loading_plot, make_loading_plot_with_confidence_intervals
from confidence import (
    bootstraped_indicators_to_dataframe,
    jacknifed_indicators_to_dataframe,
    generate_bootstraped_pcas_on_indicators,
    jacknife_and_apply_pca,
    produce_confidence_intervals,
    confidence_interval_to_dataframe
)
from stats import apply_pca, boxcox_transform

def main():
    """
    Main execution of the program.
    """

    print('Indicator data collection program')
    print('This program collects all datasets need to complete the indicator axis')
    print('This program is still under development')

    print('Reading configuration')
    config = load_config()

    print('Merging datasets')
    merged = merge_datasets(config)
    merged_dataframe = convert_dataset_to_dataframe(merged, config)
    codes = [c['id'] for c in config]

    print('Preparing indicators for PCA')
    indicators_data = prepare_dataframe_for_pca(merged_dataframe)

    print('Computing PCA on indicators')
    eigen_values, eigen_vectors, explained_variance = apply_pca(indicators_data)

    eigen_values_dataframe = DataFrame(
        eigen_values.reshape(1, len(codes)),
        columns=[f'PC {i+1}' for i in range(len(eigen_values))]
    )

    eigen_vectors_dataframe = DataFrame(
        eigen_vectors,
        columns=[f'PC {i+1}' for i in range(len(eigen_vectors))]
    )

    explained_variance_dataframe = DataFrame(
        [explained_variance],
        columns=[f'PC {i+1}' for i in range(len(explained_variance))]
    )

    make_loading_plot(eigen_vectors[:, :2], codes, './data/contribution.png')

    print('Computing degrees of independance')
    angle_matrix, independance_matrix = get_degrees_of_independance(eigen_vectors)

    angle_matrix_dataframe = DataFrame(angle_matrix, columns=codes)
    independance_matrix_dataframe = DataFrame(independance_matrix, columns=codes)

    print('Computing confidence intervals for the PCA')
    transformed_indicators = boxcox_transform(indicators_data)
    _, empiric_eigen_vector, _ = apply_pca(transformed_indicators)
    jacknifed_indicators, jacknifed_pcas = jacknife_and_apply_pca(transformed_indicators)
    jacknifed_indicators_dataframe = jacknifed_indicators_to_dataframe(
        jacknifed_indicators,
        codes
    )
    bootstraped_indicators, bootstraped_pcas = generate_bootstraped_pcas_on_indicators(
        transformed_indicators,
        empiric_eigen_vector
    )
    confidence_interval_5 = produce_confidence_intervals(
        array(bootstraped_pcas),
        jacknifed_pcas,
        empiric_eigen_vector,
        0.05
    )
    confidence_interval_1 = produce_confidence_intervals(
        array(bootstraped_pcas),
        jacknifed_pcas,
        empiric_eigen_vector,
        0.01
    )

    make_loading_plot_with_confidence_intervals(
        empiric_eigen_vector[:, :2],
        codes,
        './data/contribution-cl05.png',
        confidence_interval_5[0],
        confidence_interval_5[1]
    )
    make_loading_plot_with_confidence_intervals(
        empiric_eigen_vector[:, :2],
        codes,
        './data/contribution-cl01.png',
        confidence_interval_1[0],
        confidence_interval_1[1]
    )

    bootstraped_indicator_dataframe = bootstraped_indicators_to_dataframe(
        bootstraped_indicators,
        codes
    )
    confidence_interval_5_dataframe = confidence_interval_to_dataframe(
        confidence_interval_5[0],
        confidence_interval_5[1],
        codes
    )
    confidence_interval_1_dataframe = confidence_interval_to_dataframe(
        confidence_interval_1[0],
        confidence_interval_1[1],
        codes
    )
    empiric_eigen_vector_dataframe = DataFrame(
        eigen_vectors,
        columns=[f'PC {i+1}' for i in range(len(eigen_vectors))]
    )

    print('Computing AHP')
    scores = get_scores_for_indicators(config)
    scores_dataframe = convert_scores_to_dataframe(scores)
    indicators = scores.keys()

    comparison_matrices = get_comparison_matrices(scores)
    social_comparison_matrix_dataframe = DataFrame(
        comparison_matrices['social'],
        columns=indicators
    )
    economic_comparison_matrix_dataframe = DataFrame(
        comparison_matrices['economic'],
        columns=indicators
    )
    environmental_comparison_matrix_dataframe = DataFrame(
        comparison_matrices['environmental'],
        columns=indicators
    )

    # The eigen values will be used for the uncertainty.
    weight_vectors, consistency, final_weights = get_subjective_weights(comparison_matrices)
    weights_dataframe = convert_weights_to_dataframe(indicators, weight_vectors, final_weights)
    consistency_dataframe = convert_consistency_to_dataframe(consistency)

    print('Saving files')
    save_csv(merged_dataframe, 'merged.csv')
    save_csv(eigen_values_dataframe, 'eigen-values.csv')
    save_csv(eigen_vectors_dataframe, 'eigen-vectors.csv')
    save_csv(explained_variance_dataframe, 'explained-variance.csv')
    save_csv(angle_matrix_dataframe, 'angles.csv')
    save_csv(independance_matrix_dataframe, 'independance_degree.csv')
    save_csv(scores_dataframe, 'scores.csv')
    save_csv(social_comparison_matrix_dataframe, 'social-comparison-matrix.csv')
    save_csv(economic_comparison_matrix_dataframe, 'economic-comparison-matrix.csv')
    save_csv(environmental_comparison_matrix_dataframe, 'environmental-comparison-matrix.csv')
    save_csv(weights_dataframe, 'weights.csv')
    save_csv(consistency_dataframe, 'consistency.csv')
    save_csv(bootstraped_indicator_dataframe, 'bootstraped-data.csv')
    save_csv(jacknifed_indicators_dataframe, 'jacknifed-data.csv')
    save_csv(confidence_interval_5_dataframe, 'confidence-intervals-05.csv')
    save_csv(confidence_interval_1_dataframe, 'confidence-intervals-01.csv')
    save_csv(empiric_eigen_vector_dataframe, 'empiric-eigen-vectors.csv')


if __name__ == '__main__':
    main()
